services:

    #
    # Model builder
    #
    fos_message.model_builder:
        class: FOS\Message\ObjectBuilder\ModelBuilder
        arguments:
            - %fos_message.model_class.message%
            - %fos_message.model_class.message_metadata%
            - %fos_message.model_class.thread%
            - %fos_message.model_class.thread_metadata%

    #
    # Event dispatcher
    #
    fos_message.delegated_event_dispatcher:
        class: FOS\Message\EventDispatcher\DelegatedEventDispatcher
        arguments:
            - @event_dispatcher

    #
    # Service builder
    #
    fos_message.service_builder:
        class: FOS\Message\ObjectBuilder\ServiceBuilder
        arguments:
            - @fos_message.driver
            - @fos_message.model_builder
            - @fos_message.delegated_event_dispatcher

    #
    # Library services
    #
    fos_message.composer.default:
        class: FOS\Message\Composer\Composer
        factory_service: fos_message.service_builder
        factory_method: createComposer

    fos_message.deleter.default:
        class: FOS\Message\Deleter\Deleter
        factory_service: fos_message.service_builder
        factory_method: createDeleter

    fos_message.provider.default:
        class: FOS\Message\Provider\Provider
        factory_service: fos_message.service_builder
        factory_method: createProvider

    fos_message.reader.default:
        class: FOS\Message\Reader\Reader
        factory_service: fos_message.service_builder
        factory_method: createReader

    fos_message.remover.default:
        class: FOS\Message\Remover\Remover
        factory_service: fos_message.service_builder
        factory_method: createRemover

    fos_message.searcher.default:
        class: FOS\Message\Searcher\Searcher
        factory_service: fos_message.service_builder
        factory_method: createSearcher

    fos_message.sender.default:
        class: FOS\Message\Sender\Sender
        factory_service: fos_message.service_builder
        factory_method: createSender

    fos_message.updater.default:
        class: FOS\Message\Updater\Updater
        factory_service: fos_message.service_builder
        factory_method: createUpdater

    #
    # Repository, main entrypoint
    #
    fos_message.repository:
        class: FOS\Message\Repository
        arguments:
            - @fos_message.composer
            - @fos_message.deleter
            - @fos_message.provider
            - @fos_message.reader
            - @fos_message.sender
            - @fos_message.updater
            - @fos_message.remover

    #
    # Participant provider
    #
    fos_message.participant_provider:
        class: FOS\MessageBundle\Security\ParticipantProvider
        arguments:
            - @security.token_storage

    #
    # Authorize
    #
    fos_message.authorizer:
        class: FOS\MessageBundle\Security\Authorizer
        arguments:
            - @fos_message.participant_provider

    #
    # Twig extension
    #
    fos_message.twig_extension:
        class: FOS\MessageBundle\Twig\Extension\MessageExtension
        arguments:
            - @fos_message.participant_provider
            - @fos_message.provider
            - @fos_message.authorizer
            - @form.factory
            - @fos_message.forms.action.type
        tags:
            - { name: twig.extension }

    #
    # Bridges manager
    #
    fos_message.bridges_manager:
        class: FOS\MessageBundle\Bridge\BridgeManager
        arguments:
            - @service_container