fos_message_inbox:
    pattern: /
    defaults: { _controller: FOSMessageBundle:Message:inbox }

fos_message_sent:
    pattern: /sent
    defaults: { _controller: FOSMessageBundle:Message:sent }

fos_message_deleted:
    pattern: /deleted
    defaults: { _controller: FOSMessageBundle:Message:deleted }

fos_message_thread_new:
    pattern: /new
    defaults: { _controller: FOSMessageBundle:Message:newThread }

fos_message_thread_delete:
    pattern: /thread/{threadId}/delete
    requirements: { threadId: \d+ }
    defaults: { _controller: FOSMessageBundle:Message:delete }

fos_message_thread_undelete:
    pattern: /thread/{threadId}/undelete
    requirements: { threadId: \d+ }
    defaults: { _controller: FOSMessageBundle:Message:undelete }

fos_message_thread_view:
    pattern: /thread/{threadId}
    requirements: { threadId: \d+ }
    defaults: { _controller: FOSMessageBundle:Message:thread }