fos_message_inbox:
    path: /
    methods: [ GET ]
    defaults: { _controller: FOSMessageBundle:Message:inbox }

fos_message_sent:
    path: /sent
    methods: [ GET ]
    defaults: { _controller: FOSMessageBundle:Message:sent }

fos_message_deleted:
    path: /deleted
    methods: [ GET ]
    defaults: { _controller: FOSMessageBundle:Message:deleted }

fos_message_thread_new:
    path: /new
    methods: [ GET, POST ]
    defaults: { _controller: FOSMessageBundle:Message:new }

fos_message_thread_view:
    path: /thread/{threadId}
    requirements: { threadId: \d+ }
    methods: [ GET, POST ]
    defaults: { _controller: FOSMessageBundle:Message:thread }

fos_message_thread_delete:
    path: /thread/{threadId}/delete
    requirements: { threadId: \d+ }
    methods: [ POST ]
    defaults: { _controller: FOSMessageBundle:Message:delete }

fos_message_thread_undelete:
    path: /thread/{threadId}/undelete
    requirements: { threadId: \d+ }
    defaults: { _controller: FOSMessageBundle:Message:undelete }

fos_message_thread_read:
    path: /thread/{threadId}/read
    requirements: { threadId: \d+ }
    methods: [ POST ]
    defaults: { _controller: FOSMessageBundle:Message:read }

fos_message_thread_unread:
    path: /thread/{threadId}/unread
    requirements: { threadId: \d+ }
    defaults: { _controller: FOSMessageBundle:Message:unread }