language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer update -n

script: phpunit -v --coverage-text

notifications:
  email:
    - galopintitouan@gmail.com

matrix:
  allow_failures:
    - php: hhvm
