services:

    #
    # Driver statements paginator
    #
    fos_message.statement_paginator:
        class: FOS\MessageBundle\Bridge\KnpPaginator\Paginator\StatementPaginator
        arguments:
            - @knp_paginator